services:
  web-demo:
    build: ./challenges/intro/web-demo
    init: true
    ports:
      - "127.0.0.1:5101:5000"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    pids_limit: 64
    mem_limit: 128m
    cpus: 0.50
    networks: [web_demo_net]

  web-hard-upload-include:
    build: ./challenges/final/web/web-hard-upload-include
    init: true
    ports:
      - "127.0.0.1:5104:5000"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
      - /var/www/html/uploads:rw,noexec,nosuid,size=16m,uid=33,gid=33
      - /var/run/apache2:rw,nosuid,size=1m
      - /var/lock/apache2:rw,nosuid,size=1m
    security_opt:
      - no-new-privileges:true
    pids_limit: 64
    mem_limit: 128m
    cpus: 0.50
    networks: [web_hard_upload_include_net]

  web-bonus-xxe-docx:
    build: ./challenges/final/web/web-bonus-xxe-docx
    init: true
    ports:
      - "127.0.0.1:5105:5000"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    pids_limit: 64
    mem_limit: 128m
    cpus: 0.50
    networks: [web_bonus_xxe_docx_net]

  web-easy-method-head:
    build: ./challenges/final/web/web-easy-method-head
    init: true
    ports:
      - "127.0.0.1:5102:5000"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    pids_limit: 64
    mem_limit: 128m
    cpus: 0.50
    networks: [web_easy_method_head_net]

  web-medium-command-injection:
    build: ./challenges/final/web/web-medium-command-injection
    init: true
    ports:
      - "127.0.0.1:5103:5000"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    cap_add: [NET_RAW]
    pids_limit: 64
    mem_limit: 128m
    cpus: 0.50
    networks: [web_medium_command_injection_net]

networks:
  web_demo_net: {internal: true}
  web_hard_upload_include_net: {internal: true}
  web_bonus_xxe_docx_net: {internal: true}
  web_easy_method_head_net: {internal: true}
  web_medium_command_injection_net: {internal: true}
